name: Release

on:
    push:
        branches:
            - senpai

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: "Wait for status checks"
              id: waitforstatuschecks
              uses: "WyriHaximus/github-action-wait-for-status@v2"
              with:
                  ignoreActions: Release
                  checkInterval: 13
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install yarn
              run: npm i yarn@1.22.10 -g

            - name: Setup credentials
              shell: bash
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  rm -rf ~/.npmrc
                  touch ~/.npmrc
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

            - name: Install dependencies
              run: yarn ci

            - name: Build
              run: yarn build

            - name: Deploy
              if: steps.waitforstatuschecks.outputs.status == 'success'
              run: yarn publish --non-interactive
